import type { Metadata } from "next";
import { Providers } from "../providers";
import HeaderDashboardComponent from "@/components/Dashboard/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Providers>
        <HeaderDashboardComponent />
        {children}
      </Providers>
    </>
  );
}
